### PR TITLE
Use docker-machine and docker-compose for deploying

### PR DESCRIPTION
**Pull request by emilsoman**

### CODE REVIEW

**Comment by iffyuva** [comment]
how to test this?

**Comment by emilsoman** [comment]
@iffyuva End-to-end testing can be done using slack, but still there are some rough edges. Not yet ready for testing.

**Comment by iffyuva** [comment]
guess this can be merged then.

**Comment by emilsoman** [comment]
@iffyuva i'll do a round of testing and we'll run the commands on the slack room once and then merge. is that okay ?

**Comment by iffyuva** [comment]
yes. np

**Pull request merged**
